favicon: https://cdn.wuyuan.dev/sitelogo.png

# _config.yun.yml
medium_zoom: true

scrollreveal:
  enable: true
  targets:
    - .post-card
    - .markdown-body img

waline:
  enable: true
  serverURL: https://blog-waline-service.wuyuan.dev/
  # visitor: true
  comment: true

cursor:
  enable: true
  default: https://cdn.yunyoujun.cn/css/md-cursors/pointer.cur
  pointer: https://cdn.yunyoujun.cn/css/md-cursors/link.cur
  text: https://cdn.yunyoujun.cn/css/md-cursors/text.cur

fireworks:
  enable: true
  colors:
    - "102, 167, 221"
    - "62, 131, 225"
    - "33, 78, 194"

social:
  - name: RSS
    # set rss in your root config
    # https://github.com/hexojs/hexo-generator-feed
    link: /atom.xml # config.feed.path
    icon: ri:rss-line
    color: orange
  - name: GitHub
    link: https://github.com/sunwuyuan
    icon: ri:github-line
    color: "#181717"
  - name: E-Mail
    link: mailto:sun@wuyuan.dev
    icon: ri:mail-line
    color: "#8E71C1"
  - name: å¾®åš
    link: https://weibo.com/wuyuankeji
    icon: ri:weibo-line
    color: "#E6162D"
  - name: çŸ¥ä¹
    link: https://www.zhihu.com/people/sunwuyuan
    icon: ri:zhihu-line
    color: "#0084FF"
  - name: å“”å“©å“”å“©åŠ¨ç”»
    link: https://space.bilibili.com/661404066
    icon: ri:bilibili-line
    color: "#FF8EB3"

notice:
  enable: true
  content:
    <div style="text-align:center"><a class="site-author-avatar" href="/about/" title="å­™æ‚Ÿå…ƒ"><img width="96" loading="lazy" src="https://cdn.wuyuan.dev/sitelogo.png" alt="å­™æ‚Ÿå…ƒ"></a><br/><span class="site-name">å­™æ‚Ÿå…ƒ</span><br/>    <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-js-ripple-effect" onclick="window.location.href = 'https://status.wuyuan.dev/'">
    çŠ¶æ€
    </button>
    <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-js-ripple-effect" onclick="window.location.href = 'https://tools.wuyuan.dev/'">
    å·¥å…·
    </button>
    <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-js-ripple-effect" onclick="window.location.href = 'https://wuyuan.dev/about/'">
    å…³äº
    </button></div>

banner:
  enable: true
  #è¯·ä¿®æ”¹ä¸ºè‡ªå·±çš„ç½‘ç«™åå­—
  title: å­™æ‚Ÿå…ƒçš„å°ç«™
  border: true
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line

avatar:
  enable: true
  url: https://cdn.wuyuan.dev/sitelogo.png
  rounded: true
  opacity: 1
  mickey_mouse: false
  status:
    enable: true
    emoji: ğŸ˜­
    message: ä¸æƒ³ä¸Šå­¦

menu:
  home:
    path: /
    icon: ri:home-4-line
  list:
    - type: archives
      path: /archives/
      icon: ri:archive-line
    - type: categories
      path: /categories/
      icon: ri:folder-2-line
    - type: tags
      path: /tags/
      icon: ri:price-tag-3-line

  custom:
    title: bilibili
    path: https://space.bilibili.com/661404066
    icon: ri:bilibili-line

codeblock:
  copy_btn: true

creative_commons:
  license: by-nc-sa
  post: true
  language: deed.zh
  clipboard: true

reward:
  enable: true
  icon: ri:hand-coin-line
  comment: æ‰“èµ
  # url: https://github.com/YunYouJun/yunyoujun.github.io/issues/96
  methods:
    - name: å¾®ä¿¡æ”¯ä»˜
      path: https://img.wuyuan.dev/wxzf.png
      color: "#2DC100"
      icon: ri:wechat-pay-line

footer:
  since: 2022
  icon:
    name: ri:cloud-line
    animated: true
    color: "#0078E7"

  live_time:
    enable: false
    prefix: æœ¬åšå®¢å·²èŒèŒå“’åœ°è¿è¡Œ
    suffix: (â—'â—¡'â—)
    start_time: "2022-01-01T00:00:00"

  custom_text: <br/>ä½¿ç”¨æœ¬ç«™è§†ä¸ºåŒæ„ <a href="https://wuyuan.dev/privacy-policy/" rel="noopener" target="_blank">éšç§æ”¿ç­–</a><a href="https://icp.gov.moe/?keyword=20220591" target="_blank">èŒICPå¤‡20220591å·</a>

say:
  enable: true
  api: https://cdn.jsdelivr.net/gh/ElpsyCN/say@gh-pages/sentences.json
  # https://developer.hitokoto.cn/sentence/
  hitokoto:
    enable: true
    api: https://v1.hitokoto.cn

mourn:
  enable: true
  days:
    - 4-4

local_search:
  enable: true

baidu_push: true

head:
  css:
    example: https://code.getmdl.io/1.3.0/material.blue-light_blue.min.css
  js:
    base:
      - https://code.getmdl.io/1.3.0/material.min.js
      - https://cdn.wuyuan.dev/js/iframeResizer.contentWindow.min.js

pages:
  - name: æˆ‘çš„å°ä¼™ä¼´ä»¬
    url: /links/
    icon: ri:genderless-line
    color: dodgerblue



google_analytics:
  enable: true
  id: G-91PD6T5RP9